sudo: true
before_script:
  - sudo apt-get update -q
  - sudo apt-get remove curl
  - sudo apt-get remove zlib1g-dev
  - sudo apt-get install autoconf
  - sudo rm /usr/local/bin/bats

os: linux

dist: trusty

sudo: false

compiler: gfortran

addons:
  apt:
    packages:
    - gfortran
    - gcc
    - liblapack-dev
    - libblas-dev
    - patch

cache:
  directories:
  - $HOME/.opam/
#  - $HOME/lapack-release

language: python
python:
    - "2.7"

script: 
  - ./configure ./config/travis.cfg
#  - source ./quantum_package.rc ; cd ~ ; install_lapack.sh ; cd $QP_ROOT
  - source ./quantum_package.rc ; ninja
  - sudo apt-get install curl
  - source ./quantum_package.rc ; cd tests ; ./run_tests.sh -v
